### ISSUE TITLE
Example setup

### ISSUE THREAD

**Issue by mblarsen** [Butterwire/serverless-plugin-monorepo#5]
It would be nice with an example setup + README.

It is not obvious to me how to use this plugin. Do you create a dummy service at the root for which this plugin is installed and then more services in sub folders/workspaces.

(ps: I'm a serverless rookie, it may be painstakingly obvious to others)

**Comment by martin-css** [comment]
This plugin is designed for when you are using [Yarn workspaces](https://yarnpkg.com/lang/en/docs/workspaces/) (or some other mechanism that causes your `node_modules` folder to be hoisted below the service path).

For example. imagine the following directory layout:

```
packages/serviceA
packages/serviceB
packages/common-lib
node_modules/dep1
```

In this example. `serviceA` has dependencies on `common-lib` (in repo) & `dep1` (from NPM)

Serverless on it's own would not package up the dependencies of `serviceA` correctly as these are not present in `packages/serviceA/node_modules`.

What this plugin does is to automatically create symbolic links for all dependencies declared in the `package.json` file so that the Serverless package created contains all dependencies you require - despite these "living elsewhere".

Hope that helps a little. I will see about getting an example added but it won't be immediately.

**Comment by mblarsen** [comment]
So this mainly is useful for JavaScript projects?

You write in the docs that you have to the plugin to the serverless.yaml - would that be to serviceA/serverless.yaml serviceB/serverless.yaml in this case?

You also mention to install serverless-plugin-monorepo. Would that be the one in the root folder not shown in your example?

**Comment by martin-css** [comment]
Yes, this plugin is designed for Javascript projects.

Yes, you need to add the plugin to all `serverless.yml` files where you want to use it. So in this example, that would be both as you said.

With regards the installation, no you would not generally install in the root `package.json`. Instead you would install as a development dependency for `serviceA` & `serviceB`. Normally this would be the same version and it would end up being hoisted to the root `node_modules` but each workspace package should declare all dependencies that it needs.

**Comment by mblarsen** [comment]
Thanks @martin-css I think I got it now. 👍
